## Упражнения по библиотеке Numpy

In [1]:
import numpy as np
import math
from scipy.spatial.distance import cdist

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
random_array_1 = np.random.randint(0, 11, 20)
random_array_1[(random_array_1 > 3) & (random_array_1 < 8)] *= -1
print(random_array_1)

[ 3 -7  0  0  8 10 10  0  8  9 -4 -5 -5 -7 -5  0 -7  0 -7  2]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
random_array_2 = np.random.randint(0, 11, 20)
random_array_2[np.argmax(random_array_2)] = -1
print(random_array_2)

[-1  0  2  0  2  8  4  4  9  0  1  2  6  6  0 10  3  8  5  9]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
random_array_3 = np.array([[1,2,3], [4,5,6]])
print((random_array_3[0].reshape(-1, 1)) * (random_array_3[1]))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
array_A = np.random.randint(0, 10, size=(8, 3))
array_B = np.random.randint(0, 10, size=(2, 2))
print(array_A[(np.any(np.isin(array_A, array_B[0]), axis=1)) & (np.any(np.isin(array_A, array_B[1]), axis=1))])

[[8 3 2]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
random_martix = np.random.randint(0, 4, size=(10, 3))
random_martix[(random_martix.min(axis=1)) != (random_martix.max(axis=1))]

array([[1, 2, 0],
       [1, 2, 1],
       [0, 2, 3],
       [0, 2, 3],
       [0, 1, 2],
       [3, 2, 2],
       [3, 2, 1],
       [1, 3, 1],
       [0, 3, 3],
       [3, 0, 3]], dtype=int32)

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [7]:
Z = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 7, 7],
              [1, 2, 3],
              [7, 7, 7]])
np.unique(Z, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 7, 7]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
# Версия решения задачи с использованием Python
x_python_1 = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
prod = 1
for i in range(min(len(x_python_1), len(x_python_1[0]))):
    if x_python_1[i][i] !=0:
        prod *= x_python_1[i][i]
print(f'[Python] Ответ - {prod}')

# Версия решения задачи с использованием NumPy
x_numpy_1 = np.array([[6, 0, 9], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(f"[NumPy] Ответ - {np.prod(np.diag(x_numpy_1)[np.diag(x_numpy_1) != 0])}")

[Python] Ответ - 3
[NumPy] Ответ - 18


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [ ]:
# Версия решения с использованием Python
# x_python_2 = [[1, 2, 2, 4], [4, 2, 1, 2]]
x_python_2 = [[1, 2, 7, 4], [4, 2, 1, 2]]
print(f"[Python] Равенство мультимножеств - {sorted(x_python_2[0]) == sorted(x_python_2[1])}")

# Версия решения с использованием NumPy
# x_numpy_2 = np.array([1, 2, 8, 4])
x_numpy_2 = np.array([1, 2, 2, 4])
y_numpy_2 = np.array([4, 2, 1, 2])
print(f"[NumPy] Равенство мультимножеств - {np.all(np.sort(x_numpy_2)==np.sort(y_numpy_2))}")

[Python] Равенство мультимножеств - False
[NumPy] Равенство мультимножеств - True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
# Версия решения с использованием Python
x_python_3 = [6, 2, 0, 3, 0, 0, 5, 7, 0]
result_list = []
for i in range(0, len(x_python_3)-1):
    if x_python_3[i] == 0:
        result_list.append(x_python_3[i+1])
print(f"[Python] Максимальный элемент в векторе, имеющий перед собой 0 - {max(result_list)}")

# Версия решения с использованием NumPy
x_numpy_3 = np.array([6, 2, 0, 9, 0, 0, 5, 7, 0])
print(f"[NumPy] Максимальный элемент в векторе, имеющий перед собой 0 - {np.max((x_numpy_3[1:])[x_numpy_3[:-1] == 0])}")


[Python] Максимальный элемент в векторе, имеющий перед собой 0 - 5
[NumPy] Максимальный элемент в векторе, имеющий перед собой 0 - 9


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
# Версия решения с использованием Python
x_python_4 = [2, 2, 2, 3, 3, 3, 5]
p_numbers = [x_python_4[0]]
p_instances = [1]
for i in range(1, len(x_python_4)):
    if x_python_4[i] == x_python_4[i-1]:
        p_instances[-1] += 1
    elif x_python_4[i] != x_python_4[i-1]:
        p_numbers.append(x_python_4[i])
        p_instances.append(1)
print(f"[Python] Числа, содержащиеся в векторе - {p_numbers}, а число их повторений соответственно - {instances}")

# Версия решения с использованием NumPy
x_numpy_4 = np.array([2, 2, 2, 3, 3, 3, 5])
n_numbers = x_numpy_4[(np.concatenate(([True], x_numpy_4[:-1] != x_numpy_4[1:])))]
n_instances = np.diff(np.concatenate([[-1], np.where(x_numpy_4[:-1] != x_numpy_4[1:])[0], [len(x_numpy_4) - 1]]))
print(f"[NumPy] Числа, содержащиеся в векторе - {n_numbers} а число их повторений соответственно - {n_instances}")


[Python] Числа, содержащиеся в векторе - [2, 3, 5], а число их повторений соответственно - [3 3 1]
[NumPy] Числа, содержащиеся в векторе - [2 3 5] а число их повторений соответственно - [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
#np.random.seed(42)

X = np.random.randint(0, 10, size=(3, 2))
Y = np.random.randint(0, 10, size=(2, 2))
print(f"Выборка X содержит следующие значения:{X}")
print(f"Выборка Y содержит следующие значения:{Y}")

# Версия решения с использованием Python
distsances = []
for i_x in range(len(X)):
    for i_y in range(len(Y)):
        difference_0 = X[i_x][0] - Y[i_y][0]
        difference_1 = X[i_x][1] - Y[i_y][1]
        distsances.append(math.sqrt(difference_0**2 + difference_1**2))
print(f"[Python] Список расстояний: {distsances}")

# Версия решения с использованием NumPy
print(f"[NumPy] Список расстояний: {np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :])**2, axis=-1))}")

# Версия решения с использованием SciPy
print(f"[SciPy] Список расстояний:{cdist(X, Y)}")

Выборка X содержит следующие значения:[[2 2]
 [3 6]
 [0 0]]
Выборка Y содержит следующие значения:[[1 3]
 [7 2]]
[Python] Список расстояний: [1.4142135623730951, 5.0, 3.605551275463989, 5.656854249492381, 3.1622776601683795, 7.280109889280518]
[NumPy] Список расстояний: [[1.41421356 5.        ]
 [3.60555128 5.65685425]
 [3.16227766 7.28010989]]
[SciPy] Список расстояний:[[1.41421356 5.        ]
 [3.60555128 5.65685425]
 [3.16227766 7.28010989]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [ ]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [ ]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [ ]:
average_calories = np.mean(calorie_stats) - 60
print(f"Превышение средней калорийности над калорийностью хлопьев CrunchieMunchies - {average_calories}")

Превышение средней калорийности над калорийностью хлопев CrunchieMunchies - 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [ ]:
calorie_stats_sorted = np.sort(calorie_stats)
print(f"Сортированный список калорийности - {calorie_stats_sorted}")

Сортированный список калорийности - [ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [ ]:
median_calories = np.median(calorie_stats)
print(f"Медиана калорийности - {median_calories}")

Медиана калорий - 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [ ]:
percentiles_range = np.arange(1, 100)
percentile_values = np.percentile(calorie_stats, percentiles_range)
indices = np.where(percentile_values > 60)[0]
nth_percentile = 70 
print(f"Наименьший процентиль, превышающий 60 калорий: {nth_percentile}")

Наименьший процентиль, превышающий 60 калорий: 70


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [ ]:
more_calories = (np.mean(calorie_stats > 60)) * 100
print(f"Процент хлопьев, содержащих более 60 калорий: {more_calories}%")

Процент хлопьев, содержащих более 60 калорий: 96.1038961038961%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
calorie_std = np.std(calorie_stats)
print(f"Стандартное отклонение количества калорий: {calorie_std}")

Стандартное отклонение количества калорий: 19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
"""
Данные, полученные в результате анализа при помощи функционала NumPy, можно использовать
в маркетинговых целях, где главным драйвером рекламной кампании становятся такие преимущества
хлопьев CrunchieMunchies как:
- намного меньшая калорийность относительно средней и медианной по рынку (60 против 106/110) - .mean и .median
- нахождние калорийности далеко за пределами стандартного отколнения (в положительную сторону) - .std
- преимущество над подавляющей частью рынка (96%) по части низкой калорийности - удобное сравнение массивов с выведением среднего значения more_calories
"""

'\nДанные, полученные в результате анализа при помощи функционала NumPy, можно использовать\nв маркетинговых целях, где главным драйвером рекламной кампании становятся такие преимущества\nхлопьев CrunchieMunchies как:намного меньшая калорийность относительно средней по рынку\n'